
#will run rest tests later
name: Run Cypress Tests

on: 
  pull_request:
    branches:
      - main

jobs:
  cypress-run:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Start MongoDB
        run: |
          docker run -d -p 27017:27017 --name mongodb-instance mongo
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '16.15'
      - run: npm install --prefix client
      - run: npm install --prefix server
      - run: npm install --prefix testing
      - run: npm install
      - name: Install Cypress
        run: npm install cypress --save-dev
      - name: Cypress run
        uses: cypress-io/github-action@v5
        with:
          project: ./client
          start: npm run start --prefix client, npm run start --prefix server
          wait-on: 'http://localhost:3000,http://localhost:8000'
          browser: chrome
          timeout: 400
      - name: Stop and remove MongoDB
        run : |
          docker stop mongodb-instance
          docker rm mongodb-instance
